spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/link_in_bio_db
spring.datasource.username=marcel
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=${JWT_SECRET:ThisIsSecret}