spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/link_in_bio_db
spring.datasource.username=marcel
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=${JWT_SECRET:d98e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e}